-- Categorías
INSERT INTO Categorias (id_categoria, nombre, descripcion, estado) VALUES
(1, 'ENOTURISMO', 'Turismo relacionado con la producción y degustación de vinos.', TRUE),
(2, 'CULTURAL', 'Turismo orientado a conocer la historia, tradiciones y expresiones culturales.', TRUE),
(3, 'NATURAL', 'Turismo enfocado en la naturaleza, paisajes y recursos naturales.', TRUE),
(4, 'AVENTURA/DEPORTIVO', 'Turismo de aventura y actividades deportivas al aire libre.', TRUE);

-- SubCategorías
INSERT INTO SubCategorias (id_subcategoria, id_categoria, nombre, descripcion, estado) VALUES
(1, 1, 'Bodega', 'Visita a bodegas de vino para conocer su producción.', TRUE),
(2, 1, 'Viñedo', 'Recorrido por viñedos y plantaciones de uva.', TRUE),
(3, 1, 'Cata', 'Degustación guiada de vinos.', TRUE),
(4, 1, 'Vendimia', 'Participación en la recolección de uvas para la producción de vino.', TRUE),
(5, 1, 'Vinoteca', 'Visita a espacios especializados en la venta y conservación de vinos.', TRUE),
(6, 2, 'Arqueología', 'Turismo en sitios arqueológicos y de excavación histórica.', TRUE),
(7, 2, 'Monumento', 'Visita a monumentos y edificaciones emblemáticas.', TRUE),
(8, 2, 'Mercado', 'Recorrido por mercados tradicionales y culturales.', TRUE),
(9, 2, 'Museo', 'Visita a museos de arte, historia o ciencia.', TRUE),
(10, 2, 'Pueblo', 'Turismo en pueblos con valor histórico o cultural.', TRUE),
(11, 2, 'Festival', 'Participación en festivales culturales o tradicionales.', TRUE),
(12, 2, 'Espectáculo', 'Asistencia a espectáculos artísticos o culturales.', TRUE),
(13, 2, 'Ruta Cultural', 'Recorrido por circuitos turísticos de valor cultural.', TRUE),
(14, 2, 'Sitio Científico', 'Visita a centros o lugares de investigación científica.', TRUE),
(15, 2, 'Histórico', 'Recorrido por sitios históricos relevantes.', TRUE),
(16, 3, 'Parque Nacional', 'Visita a parques nacionales protegidos.', TRUE),
(17, 3, 'Montaña', 'Turismo en zonas montañosas y de senderismo.', TRUE),
(18, 3, 'Lago', 'Visita a lagos y cuerpos de agua naturales.', TRUE),
(19, 3, 'Río', 'Actividades turísticas en ríos.', TRUE),
(20, 3, 'Cascada', 'Visita a cascadas y saltos de agua.', TRUE),
(21, 3, 'Salar', 'Recorrido por salares y desiertos de sal.', TRUE),
(22, 3, 'Desierto', 'Turismo en regiones desérticas.', TRUE),
(23, 3, 'Playa', 'Turismo en playas y zonas costeras.', TRUE),
(24, 3, 'Fauna', 'Observación de fauna silvestre.', TRUE),
(25, 3, 'Flora', 'Observación de flora y vegetación local.', TRUE),
(26, 3, 'Mirador', 'Visita a miradores naturales o construidos.', TRUE),
(27, 3, 'Reserva Protegida', 'Turismo en reservas naturales protegidas.', TRUE),
(28, 3, 'Duna', 'Visita a dunas y paisajes arenosos.', TRUE),
(29, 3, 'Formación Geológica', 'Turismo en formaciones geológicas únicas.', TRUE),
(30, 4, 'Senderismo', 'Recorridos a pie por rutas naturales.', TRUE),
(31, 4, 'Escalada', 'Práctica de escalada en roca o montaña.', TRUE),
(32, 4, 'Ciclismo', 'Rutas y circuitos turísticos en bicicleta.', TRUE),
(33, 4, 'Acuático (Rafting, Kayak)', 'Deportes acuáticos de aventura en ríos y lagos.', TRUE),
(34, 4, 'Aéreo (Parapente)', 'Actividades aéreas como parapente o ala delta.', TRUE),
(35, 4, 'Nieve', 'Turismo en zonas de nieve y deportes invernales.', TRUE);
