-- DEPARTAMENTOS
INSERT INTO Departamentos (id_departamento, nombre, estado) VALUES
(1, 'Chuquisaca', True),
(2, 'La Paz', True),
(3, 'Cochabamba', True),
(4, 'Oruro', True),
(5, 'Potosí', True),
(6, 'Tarija', True),
(7, 'Santa Cruz', True),
(8, 'Beni', True),
(9, 'Pando', True);

-- PROVINCIAS
INSERT INTO Provincias (id_provincia, id_departamento, nombre, estado) VALUES
(1, 1, 'Oropeza', True),
(2, 1, 'Yamparáez', True),
(3, 1, 'Tomina', True),
(4, 1, 'Hernando Siles', True),
(5, 1, 'Belisario Boeto', True),
(6, 1, 'Azurduy', True),
(7, 1, 'Zudáñez', True),
(8, 1, 'Luis Calvo', True),
(9, 2, 'Murillo', True),
(10, 2, 'Los Andes', True),
(11, 2, 'Ingavi', True),
(12, 2, 'Omasuyos', True),
(13, 2, 'Pacajes', True),
(14, 2, 'Nor Yungas', True),
(15, 2, 'Sud Yungas', True),
(16, 2, 'Larecaja', True),
(17, 2, 'Franz Tamayo', True),
(18, 2, 'Muñecas', True),
(19, 2, 'Camacho', True),
(20, 2, 'Abel Iturralde', True),
(21, 3, 'Cercado', True),
(22, 3, 'Ayopaya', True),
(23, 3, 'Arque', True),
(24, 3, 'Bolívar', True),
(25, 3, 'Carrasco', True),
(26, 3, 'Campero', True),
(27, 3, 'Capinota', True),
(28, 3, 'Esteban Arce', True),
(29, 3, 'Germán Jordán', True),
(30, 3, 'Mizque', True),
(31, 3, 'Narciso Campero', True),
(32, 3, 'Punata', True),
(33, 3, 'Quillacollo', True),
(34, 3, 'Tiraque', True),
(35, 4, 'Cercado', True),
(36, 4, 'Carangas', True),
(37, 4, 'Pantaleón Dalence', True),
(38, 4, 'Ladislao Cabrera', True),
(39, 4, 'Eduardo Avaroa', True),
(40, 4, 'Sajama', True),
(41, 4, 'San Pedro de Totora', True),
(42, 4, 'Sabaya', True),
(43, 4, 'Nor Carangas', True),
(44, 4, 'Mejillones', True),
(45, 4, 'Poopó', True),
(46, 4, 'Sud Carangas', True),
(47, 5, 'Cercado', True),
(48, 5, 'Antonio Quijarro', True),
(49, 5, 'Nor Chichas', True),
(50, 5, 'Sud Chichas', True),
(51, 5, 'José María Linares', True),
(52, 5, 'Modesto Omiste', True),
(53, 5, 'Nor Lípez', True),
(54, 5, 'Sud Lípez', True),
(55, 5, 'Rafael Bustillo', True),
(56, 5, 'Tomás Frías', True),
(57, 5, 'Charcas', True),
(58, 6, 'Cercado', True),
(59, 6, 'Arce', True),
(60, 6, 'Gran Chaco', True),
(61, 6, 'Avilés', True),
(62, 6, 'O’Connor', True),
(63, 7, 'Andrés Ibáñez', True),
(64, 7, 'Warnes', True),
(65, 7, 'Ichilo', True),
(66, 7, 'Sara', True),
(67, 7, 'Florida', True),
(68, 7, 'Manuel María Caballero', True),
(69, 7, 'Chiquitos', True),
(70, 7, 'Velasco', True),
(71, 7, 'Ángel Sandóval', True),
(72, 7, 'Germán Busch', True),
(73, 7, 'Guarayos', True),
(74, 7, 'Obispo Santistevan', True),
(75, 7, 'Ñuflo de Chávez', True),
(76, 8, 'Cercado', True),
(77, 8, 'Antonio Vaca Díez', True),
(78, 8, 'Yacuma', True),
(79, 8, 'Ballivián', True),
(80, 8, 'Moxos', True),
(81, 8, 'Marbán', True),
(82, 8, 'José Ballivián', True),
(83, 8, 'Mamoré', True),
(84, 8, 'Iténez', True),
(85, 9, 'Nicolás Suárez', True),
(86, 9, 'Manuripi', True),
(87, 9, 'Abuná', True),
(88, 9, 'Federico Román', True);
